### ISSUE TITLE
Add New Line support

### ISSUE THREAD

**Issue by Rigido71** [dail8859/BetterMultiSelection#1]
Hi,
I use multiselection to create commands and, sometimes, commands need a confirmation.
With other programs (SynWrite/CudaText) I used to create "command lines", move to the end of the lines, press Enter (this will add an empty line between "command lines") and add a Y.

Step 1 - Ppaste a list of nodes:
HMD
H7D
HID
HPD
H5D

Step 2 - Use MultiLine to create "command lines":
del fil HMD *
del fil H7D *
del fil HID *
del fil HPD *
del fil H5D *

Step 3 - As del fil command need a confirmation, move to the end of each line, press Enter:
del fil HMD *

del fil H7D *

del fil HID *

del fil HPD *

del fil H5D *

Step 4 - Now there should be a caret on every new line and I can add the confirmation:
del fil HMD *
y
del fil H7D *
y
del fil HID *
y
del fil HPD *
y
del fil H5D *
y

Hope it will be possible to add this feature.

**Comment by dail8859** [comment]
Hi. Thanks for the suggestion. I've added in the ability to insert new lines. You can download the new plugin below. Just download either the 32 or 64 bit, extract it, and copy the new DLL file over your old one.

[BetterMultiSelection.zip](https://github.com/dail8859/BetterMultiSelection/files/1116144/BetterMultiSelection.zip)
[BetterMultiSelection_64.zip](https://github.com/dail8859/BetterMultiSelection/files/1116143/BetterMultiSelection_64.zip)

If you find any problems with it, just let me know.
