### ISSUE TITLE
Please add how to use to the readme file

### ISSUE THREAD

**Issue by tbird1965** [dail8859/BetterMultiSelection#11]
Your plugin looks very interesting, but I cannot perform any selections as shown in the demo gif.  I cannot find any instructions on plugin use.  The plugin is enabled.  Thank you.

**Comment by dail8859** [comment]
It should be as simple as make a selection and move the cursor.

Is this option turned on or off for you?

![image](https://user-images.githubusercontent.com/3694843/58708406-b578e980-8385-11e9-8080-04204d90f9d3.png)

**Comment by tbird1965** [comment]
I did not - that allows me to use CTRL + Left Mouse Click to select multiple items.  Follow up question - the default response of npp 7.7 seems to be similar to your readme - what does your plugin do different?

**Comment by dail8859** [comment]
> that allows me to use CTRL + Left Mouse Click to select multiple items

Good to know. Will add that to the readme that this option needs enabled.

> what does your plugin do different?

To be honest I haven't really taken the time to dig into the changes that Notepad++ v7.7 introduces with multiple selection. I know the newer version of Scintilla has better support. One thing I did find is movement of rectangular selections is not supported by Notepad++ v7.7
