### ISSUE TITLE
Autocompletion popup and SCI_AUTOCSETMULTI SC_MULTIAUTOC_EACH

### ISSUE THREAD

**Issue by vinsworldcom** [dail8859/BetterMultiSelection#13]
First off - great plugin, I just started using it and it definitely makes a difference.

I just also found SCI_AUTOCSETMULTI SC_MULTIAUTOC_EACH on [Scintilla Documentation](https://www.scintilla.org/ScintillaDoc.html#SCI_AUTOCSETMULTI) which allows me when typing in mutltiselection mode and a function or work autocomplete window pops-up, I can select and press "Enter" and the selected autocomplete is filled for ALL the multiselected cursor positions instead of just the main one.

With your plugin enabled, pressing enter in this situation ignores the autocompletion choice and just adds a carriage return at the current cursor locations.  Note that if I use the mouse to double-click the desired autocomplete selection and your plugin is enabled, I get the desired effect - the selected autocomplete is inserted at all cursor positions.  Also hitting the Tab key does the desired effect (although I have the Tab key Shortcut remapped to a QuickText plugin so I need to disable that for the Tab key to work, but it should on a default setup).  All this leads me to believe it's in the way you handle the "Enter" (VK_RETURN) key perhaps.

I wonder if you can check for SCI_AUTOCACTIVE perhaps to see if an autocompletion window is present and then ignore the "Enter" key as a newline insertion?  I haven't looked in detail at your code or all the Scintilla messages to see how to detect if an autocompletion window has popped-up.

Cheers.

**Comment by dail8859** [comment]
> All this leads me to believe it's in the way you handle the "Enter" (VK_RETURN) key perhaps.

Yep you are absolutely correct. It intercepts the `Enter` key and adds newlines instead of letting Scintilla handle it at all.

> I wonder if you can check for SCI_AUTOCACTIVE perhaps to see if an autocompletion window is present

Yes, very easily doable. 

After giving it some thought, it make sense for this plugin to enable `SC_MULTIAUTOC_EACH`. I think when using multiple cursors a user would **expect** the auto-completion to be inserted at each cursor. I cannot thing of any situation where the user would not want that to happen.

**Comment by vinsworldcom** [comment]
I like your adding that to the plugin - I agree with you that a user would
like that feature.

Thanks for the quick reply!

Cheers.

**Comment by dail8859** [comment]
You can download the latest release here:

https://github.com/dail8859/BetterMultiSelection/releases/tag/v1.4

Will get this updated in the plugin admin of no issues are found.

**Comment by vinsworldcom** [comment]
Just quickly tested - works great!!!  I also made a fix to my QuickText tab key usage to now I don't need to remap the shortcut as mentioned previously.  Now tab, enter and mouse click all do autocompletion with multi-select.

Thanks for the super quick turnaround!  See you on the N++ Community forums.

Cheers.
