### ISSUE TITLE
MultipleSelectAddNext

### ISSUE THREAD

**Issue by bitagoras** [dail8859/BetterMultiSelection#14]
In src/ScintillaEditor.h I found those two function:

- MultipleSelectAddNext()
- MultipleSelectAddEach() 

I think that this is what VSCode has bound to the shortcuts ctrl-D and shift-ctrl-L. This makes the multi selection extremely fast and versatile. Can those functions be activated and bound to keyboard shortcuts?

**Comment by dail8859** [comment]
See #12

This functionality is a bit out of scope for the plugin...but I totally agree it is incredibly useful. The whole need for the plugin is to hook the low level keyboard input. I hope that Notepad++ itself will support this natively. For now I'd recommend LuaScript (PythonScript can do this possibly as well), I've had this functionality myself for quite a few years using LuaScript.

Plus once you add this functionality then you get into configuring it such as does it match case? Whole words only? etc which means that much more that needs added to the plugin.

**Comment by bitagoras** [comment]
Ok, here is already a new feature request for this: [notepad-plus-plus #8203](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8203)
