### ISSUE TITLE
Action on selection

### ISSUE THREAD

**Issue by asvc** [dail8859/BetterMultiSelection#15]
Experiencing mild VIM withdrawal effects, I was wondering as to how one can perform an action on current selection. Your plugin comes to mind.

Say user has highlighted a word:
![image](https://user-images.githubusercontent.com/300146/81176458-56374680-8fe4-11ea-9eb8-c5c8284fd677.png)

Would it be possible to create multiple cursors based on the highlight so they can be edited simultaneously?

**Comment by dail8859** [comment]
I am not planning on adding this functionality to this plugin. See #14 and #12 for more details

I would recommend installing LuaScript. If you had the following code to the startup file:

```lua
-- Select the next occurrence of the current word
npp.AddShortcut("Selection Add Next", "Ctrl+D", function()
    local flags = SCFIND_MATCHCASE | SCFIND_WHOLEWORD -- configure options here
    editor.SearchFlags = flags

    editor:TargetWholeDocument()

    editor:MultipleSelectAddNext()
end)
```

Then you can use `Ctrl+D` to get this type of functionality:

![selectnext](https://user-images.githubusercontent.com/3694843/81181366-5b5fab80-8f7a-11ea-8bbd-83e0911312ee.gif)
