### ISSUE TITLE
Inconsistent pasting: column selection vs line selection

### ISSUE THREAD

**Issue by artie-finkelstein** [dail8859/BetterMultiSelection#16]
When a column area (Alt + mouse drag) is selected from bottom to top, copied and then pasted: the new copy is reversed by lines; this reversal does not happen with full or partial line selections made in the same bottom to top manner.  Nor does it happen in any selection method (column, line, bottom to top, or top to bottom) with version 1.3 of the BetterMultiSelection plugin.  The behavior still occurs when only the v1.4 plugin is installed (see attached debug info).  Disabling the plugin (with the enable option unchecked) BEFORE making the bottom to top column selection does prevent the reversed line order when pasting, while disabling the plugin after making the bottom to top column selection will result in the reversed line order when pasted.
[debug info.txt](https://github.com/dail8859/BetterMultiSelection/files/5064819/debug.info.txt)

**Comment by dail8859** [comment]
Thanks for the report.

I'll have to think about this some, because I would argue the current behavior is *technically* correct. However, I can see how this could cause a user to get unexpected results.

One question, if you Alt+Drag from **top to bottom**, copy, the go to another location and Alt+Drag **bottom to top** would you expect the list of words to be reversed? Or still maintain the same order?

**Comment by artie-finkelstein** [comment]
I agree on both my point and the 'technically correct' point, BUT... .
I only made the report because the full line and column area behaved
differently.  This could be fixed by the old 'if it's documented, it's
not a bug' approach.

Good question.  I expect the pasted (copy) text order to always follow
the original text order no matter which order the anchor and the caret
are created for both source and destination selections.  To me it's
just a copy operation.  Reversing line order is a separate function.
Now, as I mentioned above, other behavior is okay, just as long as it
is documented; but, I do think it's confusing to mix the concepts
(copying & reversing) unless it's done with an additional
configuration option, which let's the user decide how they want to use
it.

Humorous side note:  I was rewriting a line order reversal function
and couldn't tell the lines in the 'lorem ipsum' text apart, so I
added line number prefixes and then realized I could just use the the
line numbers by themselves, but every time I pasted the column
selection, the order was reversed, BEFORE I had even selected the new
area to test my function.  It caused me a bit of head scratching
before I finally narrowed down the cause.

As, they say down under:  "No Worries Mate".  Your wonderful plugin
has an enable option so I didn't have to remove it for plain editing
and could enable it before I wanted to do fancier editing, but over
that last couple of days I've come to realize how much I just assumed
your 'BetterMultiSelection' behavior was the default behavior, and now
I just leave it on and disable it when I plan to do column area
editing.

**Comment by dail8859** [comment]
I would guess there is a very small portion of users that this will effect, however unless someone complains, or makes a good appeal to make it configurable, then I am fine for now implementing the "expected" behavior.

As soon is appveyor is done building the new version with this change, I will post links for you to download it since it will be a while before it shows up in the Plugin Admin interface of Notepad++.

**Comment by dail8859** [comment]
32-bit: https://ci.appveyor.com/api/buildjobs/vlwj99raj97qoqwa/artifacts/BetterMultiSelection.dll
64-bit: https://ci.appveyor.com/api/buildjobs/mm5qw5k09sa086ys/artifacts/BetterMultiSelection.dll

Just download whichever DLL you need and copy over your existing `BetterMultiSelection.dll` file

**Comment by artie-finkelstein** [comment]
Cool.  I tried it out (32-bit), and as you say, it works as expected!
Thanks for the speedy fix.

BTW:  You might consider bumping the version number in the DLL.

**Comment by dail8859** [comment]
Will make an official release at some point with these changes. Thanks.
