### ISSUE TITLE
deletions at the beginning/end of lines without effect

### ISSUE THREAD

**Issue by CennoxX** [dail8859/BetterMultiSelection#18]
**delete key on line end**
If I press the delete key on the line end, while having multiple cursors, nothing happens.
I can simulate the expected behaviour by pressing `[shift]`+`[right]` and `[delete]`
![output](https://user-images.githubusercontent.com/6975881/149746410-bb3a1f46-ec54-4a29-88e7-76936e8a10e0.gif)

**backspace on line start**
Same problem on line start, while having multiple cursors, and pressing backspace, though this works for example, if I pressed enter before.
![output2](https://user-images.githubusercontent.com/6975881/149748203-67991ca5-f87d-46a5-811d-31d245a25a88.gif)

**Comment by dail8859** [comment]
Closed by 0a0ee31035da3f186636621b3d3d393db23cca24
