### ISSUE TITLE
Support SCI_DELWORDLEFT (Ctrl+Backspace) and SCI_DELWORDRIGHT (Ctrl+DEL) commands

### ISSUE THREAD

**Issue by marcobaldelli** [dail8859/BetterMultiSelection#3]
Hi,

thanks for this plug-in, it's very useful.

I was wondering if it would be possible to support Scintilla's SCI_DELWORDLEFT (Ctrl+Backspace) and SCI_DELWORDRIGHT (Ctrl+DEL) commands.

Suppose I have three lines (`|` represents the multi-cursors):

```
one|
two two|
three three three|
```

If I invoke SCI_DELWORDLEFT (Ctrl+Backspace) I would expect the last word of each line to be removed, obtaining this result:

```
|
two|
three three|
```

Instead, this is the actual result:

```
one|
two two|
three three |
```

Likewise, if I put the multicursors at the beginning of the lines:

```
|one
|two two
|three three three
```

and I invoke SCI_DELWORDRIGHT (Ctrl+DEL) I would expect the first word of each line to be removed, obtaining this result:

```
|
|two
|three three
```

Instead, this is the actual result:

```
|one
|two two
|three three
```

Thanks.

**Comment by dail8859** [comment]
Excellent suggestion. I rarely if ever used those commands so didn't even think to consider them. You can download the updated plugin on appveyor ([32bit](https://ci.appveyor.com/project/dail8859/BetterMultiSelection/branch/master/job/b7h6hpwsawxworkh/artifacts) and [64bit](https://ci.appveyor.com/project/dail8859/BetterMultiSelection/branch/master/job/rh3glem970jorftx/artifacts)). Just download the DLL and copy over your existing DLL.

If you run into any problems let me know!
