### ISSUE TITLE
Question about QScintilla multiselection

### ISSUE THREAD

**Issue by brupelo** [dail8859/BetterMultiSelection#4]
Hiya :)

I'd like to ask you something even if the question is not exactly related to your particular amazing project (just saw one gif showing the features and it looks really nice one)... So, how difficult would be implementing a similar behaviour on pyqt's QScintilla widget such as your project is doing right now on notepad++?

Asking you this cos 1 year ago I was aware Scintilla already was providing `SCI_SETADDITIONALSELECTIONTYPING` and `SCI_ADDSELECTION` tokens, but just using those wouldn't provide a nice multiselection behaviour like in SublimeText or your plugin... so yeah, how difficult do you think it'd be to achieve?

Thanks in advance.

**Comment by dail8859** [comment]
> So, how difficult would be implementing a similar behaviour on pyqt's QScintilla widget such as your project is doing right now on notepad++?

In theory not that hard at all. 

> Scintilla already was providing `SCI_SETADDITIONALSELECTIONTYPING`

A few notes about this:
- Notepad++ is on a fairly old version of Scintilla (v3.5.6)
- In v3.6 the "additional selection typing" features got some enhancements. Quote from the Scintilla log for v3.6:
> Multiple selection now works over more key commands. The new multiple-selection handling commands include horizontal movement and selection commands, line up and down movement and selection commands, word and line deletion commands, and line end insertion. This change in behaviours is conditional on setting the SCI_SETADDITIONALSELECTIONTYPING property. 
- Even with this enhancement Scintilla does not do what I would like from it. The "default" behavior is only applicable to *multiple, individual selections*, which are normally created by `Ctrl+Left Click`ing several times.

I think the core benefit of this plugin is to turn a single rectangular selection into multiple individual selections. I wish this was a core feature or option within Scintilla...maybe some day.

> how difficult do you think it'd be to achieve?

The plugin achieves this by hooking the keyboard and catching the input before Scintilla does...which is fairly straight forward for Windows. I think the equivalent with Qt5 would be a widget's [keyPressEvent](https://doc.qt.io/qt-5/qwidget.html#keyPressEvent) and just look for the keys you need. My implementation is kind of hackish and has some oddities...but it works for the most part. 

Take a look at this function:

https://github.com/dail8859/BetterMultiSelection/blob/b41708bbffbbf7da0d0c817da1e153ac1deb5a7c/src/Main.cpp#L333-L381

which is where it processes they keyboard input.

**Comment by dail8859** [comment]
FYI I've simplified the logic quite a bit now in the master branch, so the logic should be even easier to understand.

If you have any other questions just let me know.
