### ISSUE TITLE
Add up/down support

### ISSUE THREAD

**Issue by KaKi87** [dail8859/BetterMultiSelection#6]
Hello,

You have home/end/left/right, let's add up and down.

Unfortunately I can't tell you how to program it, but that's my suggestion. xD

Thanks !

**Comment by dail8859** [comment]
I've never found a need to use up/down myself...but I guess others might find it useful.

**Comment by KaKi87** [comment]
Thanks, but I can't do it even after re-downloading the DLL file ?

> I've never found a need to use up/down myself

Well, I need it when I want to edit at multiple positions but one line at a time.

**Comment by dail8859** [comment]
The code has been modified but no release of a new version has been created. Until then you can manually download one of the appveyor builds

- 64 bit https://ci.appveyor.com/project/dail8859/bettermultiselection/build/job/55qp2ws8ec5vl1dt/artifacts
- 32 bit https://ci.appveyor.com/project/dail8859/bettermultiselection/build/job/ps4mr4q51q3lx4fc/artifacts

Download the DLL and copy over your existing one.
